version: 2.1

orbs:
  node: circleci/node@5

jobs:
  build:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Install dependencies
          command: yarn
      - run:
          name: Build the application
          command: yarn build

  deploy:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - run:
          name: Install Firebase Tools
          command: yarn global add firebase-tools
      - run:
          name: Enable Firebase Web Frameworks Experiment
          command: firebase experiments:enable webframeworks
      - run:
          name: Deploy to Firebase
          command: |
            echo $GOOGLE_APPLICATION_CREDENTIALS | base64 --decode > /tmp/credentials.json
            export GOOGLE_APPLICATION_CREDENTIALS="/tmp/credentials.json"
            firebase deploy

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build