version: 2.1

orbs:
  node: circleci/node@5  # Use the CircleCI Node.js orb

jobs:
  build:
    docker:
      - image: circleci/node:14  # Use the Node.js 14 Docker image
    steps:
      - checkout  # Check out the code from the repository
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Run tests
          command: yarn test  # Run tests defined in package.json
      - run:
          name: Build the application
          command: yarn build  # Build the Next.js application

  deploy:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run:
          name: Install Firebase Tools
          command: yarn global add firebase-tools  # Install Firebase CLI using Yarn
      - run:
          name: Deploy to Firebase
          command: |
            echo $FIREBASE_TOKEN | firebase deploy --token "$FIREBASE_TOKEN"  # Deploy to Firebase Hosting

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build  # Ensure the deploy job runs after the build job
