version: 2.1

orbs:
  node: circleci/node@5  # Use the CircleCI Node.js orb

jobs:
  build:
    docker:
      - image: cimg/node:lts  # Use the Node.js LTS version of the Docker image
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Install dependencies
          command: yarn
      - run:
          name: Build the application
          command: yarn build  # Build the Next.js application
      - persist_to_workspace:
          root: .
          paths:
            - public
            - .cache
            - firebase.json
            - .firebaserc

  deploy:
    docker:
      - image: cimg/node:lts  # Use the Node.js LTS version of the Docker image
    steps:
      - checkout
      - run:
          name: Install Firebase Tools
          command: yarn global add firebase-tools  # Install Firebase CLI using Yarn
      - run:
          name: Enable Firebase Web Frameworks Experiment
          command: firebase experiments:enable webframeworks
      - run:
          name: Deploy to Firebase
          command: |
            echo $FIREBASE_TOKEN
            firebase --version
            firebase use firebase-sandbox
            firebase deploy --only hosting --token "$FIREBASE_TOKEN"
            echo $?

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build  # Ensure the deploy job runs after the build job.